version: "2"
services:
  aria2-pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    #user: "956000010:956000008"
    environment:
      - PUID=956000010
      - PGID=956000008
      - UMASK_SET=002
      - RPC_SECRET=Secret
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Europe/Paris
    volumes:
      - /datas/appsNFS/aria2/aria2-config:/config
      - /datas/appsNFS/aria2/aria2-downloads:/downloads
# If you use host network mode, then no port mapping is required.
# This is your best choice when using IPv6.
    network_mode: host
#    ports:
#      - 6800:6800
#      - 6888:6888
#      - 6888:6888/udp
    restart: unless-stopped
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m
# AriaNg is just a static web page, usually you only need to deploy on a single host.
  ariang:
    container_name: ariang
    image: p3terx/ariang
    network_mode: bridge
    ports:
      - 6880:6880
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
 
  automated-dl:
    container_name: automated-dl
    image: poppypop/automated-dl
    user: "956000010:956000008"
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - /datas/appsNFS/aria2/aria2-downloads:/downloads
    environment:
      - SERVER=http://datas.moot.ovh
      - SECRET=Secret
    logging:
      driver: json-file
      options:
        max-size: 1m 
