version: "2"
services:
  jellyfin:
    container_name: media-sort
    image: chaudhryfaisal/media-sort
    user: "956000010:956000008"
    environment:
      - TZ=Europe/Paris
    volumes:
      - /datas:/datas
    restart: unless-stopped
    command: -t /datas/Shares/Media/Series/ -m /datas/Shares/Media/Films/ --tv-template '{{ .Name }}/S{{ printf "%02d" .Season }}/{{ .Name }} S{{ printf "%02d" .Season }}E{{ printf "%02d" .Episode }}{{ if ne .ExtraEpisode -1 }}-{{ printf "%02d" .ExtraEpisode }}{{end}}.{{ .Ext }}' -r -s -w /datas/appsNFS/aria2/dl/downloads/Ended/
#  limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m
