version: "2"
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    user: "956000010:956000008"
    environment:
      - TZ=Europe/Paris
      #- JELLYFIN_PublishedServerUrl=http://dl.moot.ovh
    volumes:
      - /datas/appsNFS/jellyfin/config:/config
      - jellyfin-cache:/cache
      - /datas/appsNFS/aria2/aria2-downloads/Ended:/downloads
      - /datas/Shares/Media:/media
    networks:
      macvlan:
        ipv4_address: 10.0.3.2
    restart: unless-stopped
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m
networks:
  macvlan:
    external:
      name: macvlan
